---
- name: Az login with managed identity
  shell: az login --identity
  changed_when: false

- name: Az ACR login
  shell: az acr login --name ggstream
  changed_when: false
  register: az_acr_login

- debug: msg="{{ az_acr_login.stdout }}"