---
- name: Add Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add Azure CLI repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/azure-cli/ bionic main
    state: present

- name: Install Azure CLI
  apt:
    update_cache: yes
    name: azure-cli
    state: latest
