---
- name: Install dependencies
  apt: 
    update_cache: yes
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python-setuptools
      - python3-setuptools
      - git
    state: latest